# Generated by Django 3.2.7 on 2021-11-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0002_auto_20211009_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='display_name',
            field=models.CharField(blank=True, default='ERROR', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(blank=True, default='ERROR', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(blank=True, default='ERROR', max_length=20),
        ),
    ]
