# Generated by Django 3.2.7 on 2021-12-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0004_auto_20211117_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_last', models.IntegerField()),
                ('chart_color', models.CharField(blank=True, max_length=7, null=True)),
                ('min_error_value', models.FloatField()),
                ('max_error_value', models.FloatField()),
            ],
        ),
    ]
