# Generated by Django 3.2.7 on 2021-12-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_app', '0005_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_color', models.CharField(blank=True, max_length=7, null=True)),
                ('min_error_value', models.FloatField()),
                ('max_error_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_last', models.IntegerField()),
            ],
        ),
    ]
