# Generated by Django 3.2.7 on 2021-10-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushfarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relay',
            name='mode',
            field=models.CharField(choices=[('MANUAL', 'MANUAL'), ('AUTO', 'AUTO'), ('SENSOR', 'SENSOR'), ('TIME_1', 'TIME_1'), ('TIME_2', 'TIME_2')], default='MANUAL', max_length=6),
        ),
    ]
