# Generated by Django 3.2.7 on 2021-12-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_color', models.CharField(blank=True, max_length=7, null=True)),
                ('min_error_value', models.FloatField()),
                ('max_error_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_last', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChartSettings', models.ManyToManyField(to='station_settings.ChartSetting')),
                ('DashboardSettings', models.ManyToManyField(to='station_settings.DashboardSetting')),
            ],
        ),
    ]
