# Generated by Django 3.2.7 on 2021-12-16 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('list_of_indexes', models.CharField(default='[]', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='chartsetting',
            name='chart_color',
            field=models.CharField(default='#0000FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='chartsetting',
            name='max_error_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chartsetting',
            name='min_error_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardsetting',
            name='time_last',
            field=models.IntegerField(default=24),
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AddField(
            model_name='group',
            name='ChartSettings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='station_settings.chartsetting'),
        ),
        migrations.AddField(
            model_name='group',
            name='DashboardSettings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='station_settings.dashboardsetting'),
        ),
    ]
