# Generated by Django 3.2.7 on 2021-12-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_settings', '0004_auto_20211216_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
