# Generated by Django 3.2.7 on 2021-12-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_settings', '0005_group_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='index',
        ),
    ]
