# Generated by Django 3.2.7 on 2022-05-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_settings', '0006_remove_group_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='list_of_indexes',
            field=models.CharField(default='[]', max_length=2000),
        ),
    ]
